### ISSUE TITLE
Basic Type Outline Mega Checklist

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/hektor#4]
We want to do these things just because they're Rust considerations, not because they all make geometric sense. Not every step will be appropriate to all types, just skip steps that don't fit.

### ivec2

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### ivec3

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### ivec4

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat2

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat2x3

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat2x4

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat3

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat3x2

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat3x4

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat4

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat4x2

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### mat4x3

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### quat

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### vec2

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### vec3

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign

### vec4

* [ ] Module / Declaration / Derives
* [ ] Deref / DerefMut (this makes things immediately easier to use)
* [ ] PartialEq / Eq (this lets us `assert_eq!` in tests for all things below)
* [ ] Zero / One / Identity etc const functions
* [ ] Add / AddAssign
* [ ] BitAnd / BitAndAssign
* [ ] BitXor / BitXorAssign
* [ ] Div / DivAssign
* [ ] Index / IndexMut
* [ ] Mul / MulAssign
* [ ] Neg
* [ ] Not
* [ ] Rem / RemAssign
* [ ] Shl / ShlAssign
* [ ] Shr / ShrAssign
* [ ] Sub / SubAssign
