### ISSUE TITLE
SSE2 Mega Checklist

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/hektor#5]
For entertainment purposes only, I'm checking off boxes if I use an intrinsic at least once within the lib.

Kept up to date as often as I remember to do it.

* [ ] _m_maskmovq(__m64 a, __m64 mask, char* mem_addr) -> void
* [ ] _m_pavgb(__m64 a, __m64 b) -> __m64
* [ ] _m_pavgw(__m64 a, __m64 b) -> __m64
* [ ] _m_pextrw(__m64 a, int imm8) -> int
* [ ] _m_pinsrw(__m64 a, int i, int imm8) -> __m64
* [ ] _m_pmaxsw(__m64 a, __m64 b) -> __m64
* [ ] _m_pmaxub(__m64 a, __m64 b) -> __m64
* [ ] _m_pminsw(__m64 a, __m64 b) -> __m64
* [ ] _m_pminub(__m64 a, __m64 b) -> __m64
* [ ] _m_pmovmskb(__m64 a) -> int
* [ ] _m_pmulhuw(__m64 a, __m64 b) -> __m64
* [ ] _m_psadbw(__m64 a, __m64 b) -> __m64
* [ ] _m_pshufw(__m64 a, int imm8) -> __m64
* [ ] _mm_add_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_add_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_add_epi64(__m128i a, __m128i b) -> __m128i
* [ ] _mm_add_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_add_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_add_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_add_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_add_si64(__m64 a, __m64 b) -> __m64
* [x] _mm_add_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_adds_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_adds_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_adds_epu16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_adds_epu8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_and_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_and_ps(__m128 a, __m128 b) -> __m128
* [x] _mm_and_si128(__m128i a, __m128i b) -> __m128i
* [ ] _mm_andnot_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_andnot_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_andnot_si128(__m128i a, __m128i b) -> __m128i
* [ ] _mm_avg_epu16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_avg_epu8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_avg_pu16(__m64 a, __m64 b) -> __m64
* [ ] _mm_avg_pu8(__m64 a, __m64 b) -> __m64
* [ ] _mm_bslli_si128(__m128i a, int imm8) -> __m128i
* [ ] _mm_bsrli_si128(__m128i a, int imm8) -> __m128i
* [ ] _mm_castpd_ps(__m128d a) -> __m128
* [ ] _mm_castpd_si128(__m128d a) -> __m128i
* [ ] _mm_castps_pd(__m128 a) -> __m128d
* [ ] _mm_castps_si128(__m128 a) -> __m128i
* [ ] _mm_castsi128_pd(__m128i a) -> __m128d
* [ ] _mm_castsi128_ps(__m128i a) -> __m128
* [ ] _mm_clflush(void const* p) -> void
* [ ] _mm_cmpeq_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmpeq_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmpeq_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmpeq_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_cmpeq_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpeq_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpeq_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpge_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpge_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpge_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpge_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpgt_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmpgt_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmpgt_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmpgt_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpgt_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpgt_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpgt_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmple_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmple_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmple_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmple_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmplt_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmplt_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmplt_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmplt_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmplt_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmplt_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmplt_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpneq_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_cmpneq_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpneq_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpneq_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpnge_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpnge_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpnge_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpnge_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpngt_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpngt_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpngt_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpngt_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpnle_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpnle_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpnle_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpnle_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpnlt_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpnlt_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpnlt_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpnlt_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpord_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpord_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpord_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpord_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpunord_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpunord_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpunord_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_cmpunord_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_comieq_sd(__m128d a, __m128d b) -> int
* [ ] _mm_comieq_ss(__m128 a, __m128 b) -> int
* [ ] _mm_comige_sd(__m128d a, __m128d b) -> int
* [ ] _mm_comige_ss(__m128 a, __m128 b) -> int
* [ ] _mm_comigt_sd(__m128d a, __m128d b) -> int
* [ ] _mm_comigt_ss(__m128 a, __m128 b) -> int
* [ ] _mm_comile_sd(__m128d a, __m128d b) -> int
* [ ] _mm_comile_ss(__m128 a, __m128 b) -> int
* [ ] _mm_comilt_sd(__m128d a, __m128d b) -> int
* [ ] _mm_comilt_ss(__m128 a, __m128 b) -> int
* [ ] _mm_comineq_sd(__m128d a, __m128d b) -> int
* [ ] _mm_comineq_ss(__m128 a, __m128 b) -> int
* [ ] _mm_cvt_pi2ps(__m128 a, __m64 b) -> __m128
* [ ] _mm_cvt_ps2pi(__m128 a) -> __m64
* [ ] _mm_cvt_si2ss(__m128 a, int b) -> __m128
* [ ] _mm_cvt_ss2si(__m128 a) -> int
* [ ] _mm_cvtepi32_pd(__m128i a) -> __m128d
* [x] _mm_cvtepi32_ps(__m128i a) -> __m128
* [ ] _mm_cvtpd_epi32(__m128d a) -> __m128i
* [ ] _mm_cvtpd_pi32(__m128d a) -> __m64
* [ ] _mm_cvtpd_ps(__m128d a) -> __m128
* [ ] _mm_cvtpi16_ps(__m64 a) -> __m128
* [ ] _mm_cvtpi32_pd(__m64 a) -> __m128d
* [ ] _mm_cvtpi32_ps(__m128 a, __m64 b) -> __m128
* [ ] _mm_cvtpi32x2_ps(__m64 a, __m64 b) -> __m128
* [ ] _mm_cvtpi8_ps(__m64 a) -> __m128
* [x] _mm_cvtps_epi32(__m128 a) -> __m128i
* [ ] _mm_cvtps_pd(__m128 a) -> __m128d
* [ ] _mm_cvtps_pi16(__m128 a) -> __m64
* [ ] _mm_cvtps_pi32(__m128 a) -> __m64
* [ ] _mm_cvtps_pi8(__m128 a) -> __m64
* [ ] _mm_cvtpu16_ps(__m64 a) -> __m128
* [ ] _mm_cvtpu8_ps(__m64 a) -> __m128
* [ ] _mm_cvtsd_f64(__m128d a) -> double
* [ ] _mm_cvtsd_si32(__m128d a) -> int
* [ ] _mm_cvtsd_si64(__m128d a) -> __int64
* [ ] _mm_cvtsd_si64x(__m128d a) -> __int64
* [ ] _mm_cvtsd_ss(__m128 a, __m128d b) -> __m128
* [ ] _mm_cvtsi128_si32(__m128i a) -> int
* [ ] _mm_cvtsi128_si64(__m128i a) -> __int64
* [ ] _mm_cvtsi128_si64x(__m128i a) -> __int64
* [ ] _mm_cvtsi32_sd(__m128d a, int b) -> __m128d
* [ ] _mm_cvtsi32_si128(int a) -> __m128i
* [ ] _mm_cvtsi32_ss(__m128 a, int b) -> __m128
* [ ] _mm_cvtsi64_sd(__m128d a, __int64 b) -> __m128d
* [ ] _mm_cvtsi64_si128(__int64 a) -> __m128i
* [ ] _mm_cvtsi64_ss(__m128 a, __int64 b) -> __m128
* [ ] _mm_cvtsi64x_sd(__m128d a, __int64 b) -> __m128d
* [ ] _mm_cvtsi64x_si128(__int64 a) -> __m128i
* [x] _mm_cvtss_f32(__m128 a) -> float
* [ ] _mm_cvtss_sd(__m128d a, __m128 b) -> __m128d
* [ ] _mm_cvtss_si32(__m128 a) -> int
* [ ] _mm_cvtss_si64(__m128 a) -> __int64
* [ ] _mm_cvtt_ps2pi(__m128 a) -> __m64
* [ ] _mm_cvtt_ss2si(__m128 a) -> int
* [ ] _mm_cvttpd_epi32(__m128d a) -> __m128i
* [ ] _mm_cvttpd_pi32(__m128d a) -> __m64
* [ ] _mm_cvttps_epi32(__m128 a) -> __m128i
* [ ] _mm_cvttps_pi32(__m128 a) -> __m64
* [ ] _mm_cvttsd_si32(__m128d a) -> int
* [ ] _mm_cvttsd_si64(__m128d a) -> __int64
* [ ] _mm_cvttsd_si64x(__m128d a) -> __int64
* [ ] _mm_cvttss_si32(__m128 a) -> int
* [ ] _mm_cvttss_si64(__m128 a) -> __int64
* [ ] _mm_div_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_div_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_div_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_div_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_extract_epi16(__m128i a, int imm8) -> int
* [ ] _mm_extract_pi16(__m64 a, int imm8) -> int
* [ ] _mm_free(void * mem_addr) -> void
* [ ] _MM_GET_EXCEPTION_MASK() -> unsigned int
* [ ] _MM_GET_EXCEPTION_STATE() -> unsigned int
* [ ] _MM_GET_FLUSH_ZERO_MODE() -> unsigned int
* [ ] _MM_GET_ROUNDING_MODE() -> unsigned int
* [ ] _mm_getcsr(void) -> unsigned int
* [ ] _mm_insert_epi16(__m128i a, int i, int imm8) -> __m128i
* [ ] _mm_insert_pi16(__m64 a, int i, int imm8) -> __m64
* [ ] _mm_lfence(void) -> void
* [ ] _mm_load_pd(double const* mem_addr) -> __m128d
* [ ] _mm_load_pd1(double const* mem_addr) -> __m128d
* [x] _mm_load_ps(float const* mem_addr) -> __m128
* [ ] _mm_load_ps1(float const* mem_addr) -> __m128
* [ ] _mm_load_sd(double const* mem_addr) -> __m128d
* [ ] _mm_load_si128(__m128i const* mem_addr) -> __m128i
* [ ] _mm_load_ss(float const* mem_addr) -> __m128
* [ ] _mm_load1_pd(double const* mem_addr) -> __m128d
* [ ] _mm_load1_ps(float const* mem_addr) -> __m128
* [ ] _mm_loadh_pd(__m128d a, double const* mem_addr) -> __m128d
* [ ] _mm_loadh_pi(__m128 a, __m64 const* mem_addr) -> __m128
* [ ] _mm_loadl_epi64(__m128i const* mem_addr) -> __m128i
* [ ] _mm_loadl_pd(__m128d a, double const* mem_addr) -> __m128d
* [ ] _mm_loadl_pi(__m128 a, __m64 const* mem_addr) -> __m128
* [ ] _mm_loadr_pd(double const* mem_addr) -> __m128d
* [ ] _mm_loadr_ps(float const* mem_addr) -> __m128
* [ ] _mm_loadu_pd(double const* mem_addr) -> __m128d
* [ ] _mm_loadu_ps(float const* mem_addr) -> __m128
* [ ] _mm_loadu_si128(__m128i const* mem_addr) -> __m128i
* [ ] _mm_loadu_si16(void const* mem_addr) -> __m128i
* [ ] _mm_loadu_si32(void const* mem_addr) -> __m128i
* [ ] _mm_loadu_si64(void const* mem_addr) -> __m128i
* [ ] _mm_madd_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_malloc(size_t size, size_t align) -> void*
* [ ] _mm_maskmove_si64(__m64 a, __m64 mask, char* mem_addr) -> void
* [ ] _mm_maskmoveu_si128(__m128i a, __m128i mask, char* mem_addr) -> void
* [ ] _mm_max_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_max_epu8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_max_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_max_pi16(__m64 a, __m64 b) -> __m64
* [ ] _mm_max_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_max_pu8(__m64 a, __m64 b) -> __m64
* [ ] _mm_max_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_max_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_mfence(void) -> void
* [ ] _mm_min_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_min_epu8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_min_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_min_pi16(__m64 a, __m64 b) -> __m64
* [ ] _mm_min_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_min_pu8(__m64 a, __m64 b) -> __m64
* [ ] _mm_min_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_min_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_move_epi64(__m128i a) -> __m128i
* [ ] _mm_move_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_move_ss(__m128 a, __m128 b) -> __m128
* [x] _mm_movehl_ps(__m128 a, __m128 b) -> __m128
* [x] _mm_movelh_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_movemask_epi8(__m128i a) -> int
* [ ] _mm_movemask_pd(__m128d a) -> int
* [ ] _mm_movemask_pi8(__m64 a) -> int
* [x] _mm_movemask_ps(__m128 a) -> int
* [ ] _mm_movepi64_pi64(__m128i a) -> __m64
* [ ] _mm_movpi64_epi64(__m64 a) -> __m128i
* [ ] _mm_mul_epu32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_mul_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_mul_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_mul_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_mul_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_mul_su32(__m64 a, __m64 b) -> __m64
* [ ] _mm_mulhi_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_mulhi_epu16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_mulhi_pu16(__m64 a, __m64 b) -> __m64
* [ ] _mm_mullo_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_or_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_or_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_or_si128(__m128i a, __m128i b) -> __m128i
* [ ] _mm_packs_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_packs_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_packus_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_pause(void) -> void
* [ ] _mm_prefetch(char const* p, int i) -> void
* [ ] _mm_rcp_ps(__m128 a) -> __m128
* [ ] _mm_rcp_ss(__m128 a) -> __m128
* [ ] _mm_rsqrt_ps(__m128 a) -> __m128
* [ ] _mm_rsqrt_ss(__m128 a) -> __m128
* [ ] _mm_sad_epu8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_sad_pu8(__m64 a, __m64 b) -> __m64
* [ ] _mm_set_epi16(short e7, short e6, short e5, short e4, short e3, short e2, short e1, short e0) -> __m128i
* [ ] _mm_set_epi32(int e3, int e2, int e1, int e0) -> __m128i
* [ ] _mm_set_epi64(__m64 e1, __m64 e0) -> __m128i
* [ ] _mm_set_epi64x(__int64 e1, __int64 e0) -> __m128i
* [ ] _mm_set_epi8(char e15, char e14, char e13, char e12, char e11, char e10, char e9, char e8, char e7, char e6, char e5, char e4, char e3, char e2, char e1, char e0) -> __m128i
* [ ] _MM_SET_EXCEPTION_MASK(unsigned int a) -> void
* [ ] _MM_SET_EXCEPTION_STATE(unsigned int a) -> void
* [ ] _MM_SET_FLUSH_ZERO_MODE(unsigned int a) -> void
* [ ] _mm_set_pd(double e1, double e0) -> __m128d
* [ ] _mm_set_pd1(double a) -> __m128d
* [ ] _mm_set_ps(float e3, float e2, float e1, float e0) -> __m128
* [ ] _mm_set_ps1(float a) -> __m128
* [ ] _MM_SET_ROUNDING_MODE(unsigned int a) -> void
* [ ] _mm_set_sd(double a) -> __m128d
* [ ] _mm_set_ss(float a) -> __m128
* [ ] _mm_set1_epi16(short a) -> __m128i
* [ ] _mm_set1_epi32(int a) -> __m128i
* [ ] _mm_set1_epi64(__m64 a) -> __m128i
* [ ] _mm_set1_epi64x(__int64 a) -> __m128i
* [ ] _mm_set1_epi8(char a) -> __m128i
* [ ] _mm_set1_pd(double a) -> __m128d
* [ ] _mm_set1_ps(float a) -> __m128
* [ ] _mm_setcsr(unsigned int a) -> void
* [ ] _mm_setr_epi16(short e7, short e6, short e5, short e4, short e3, short e2, short e1, short e0) -> __m128i
* [ ] _mm_setr_epi32(int e3, int e2, int e1, int e0) -> __m128i
* [ ] _mm_setr_epi64(__m64 e1, __m64 e0) -> __m128i
* [ ] _mm_setr_epi8(char e15, char e14, char e13, char e12, char e11, char e10, char e9, char e8, char e7, char e6, char e5, char e4, char e3, char e2, char e1, char e0) -> __m128i
* [ ] _mm_setr_pd(double e1, double e0) -> __m128d
* [ ] _mm_setr_ps(float e3, float e2, float e1, float e0) -> __m128
* [ ] _mm_setzero_pd(void) -> __m128d
* [ ] _mm_setzero_ps(void) -> __m128
* [ ] _mm_setzero_si128() -> __m128i
* [ ] _mm_sfence(void) -> void
* [ ] _mm_shuffle_epi32(__m128i a, int imm8) -> __m128i
* [ ] _mm_shuffle_pd(__m128d a, __m128d b, int imm8) -> __m128d
* [ ] _mm_shuffle_pi16(__m64 a, int imm8) -> __m64
* [x] _mm_shuffle_ps(__m128 a, __m128 b, unsigned int imm8) -> __m128
* [ ] _mm_shufflehi_epi16(__m128i a, int imm8) -> __m128i
* [ ] _mm_shufflelo_epi16(__m128i a, int imm8) -> __m128i
* [ ] _mm_sll_epi16(__m128i a, __m128i count) -> __m128i
* [ ] _mm_sll_epi32(__m128i a, __m128i count) -> __m128i
* [ ] _mm_sll_epi64(__m128i a, __m128i count) -> __m128i
* [ ] _mm_slli_epi16(__m128i a, int imm8) -> __m128i
* [ ] _mm_slli_epi32(__m128i a, int imm8) -> __m128i
* [ ] _mm_slli_epi64(__m128i a, int imm8) -> __m128i
* [ ] _mm_slli_si128(__m128i a, int imm8) -> __m128i
* [ ] _mm_sqrt_pd(__m128d a) -> __m128d
* [ ] _mm_sqrt_ps(__m128 a) -> __m128
* [ ] _mm_sqrt_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_sqrt_ss(__m128 a) -> __m128
* [ ] _mm_sra_epi16(__m128i a, __m128i count) -> __m128i
* [ ] _mm_sra_epi32(__m128i a, __m128i count) -> __m128i
* [ ] _mm_srai_epi16(__m128i a, int imm8) -> __m128i
* [ ] _mm_srai_epi32(__m128i a, int imm8) -> __m128i
* [ ] _mm_srl_epi16(__m128i a, __m128i count) -> __m128i
* [ ] _mm_srl_epi32(__m128i a, __m128i count) -> __m128i
* [ ] _mm_srl_epi64(__m128i a, __m128i count) -> __m128i
* [ ] _mm_srli_epi16(__m128i a, int imm8) -> __m128i
* [ ] _mm_srli_epi32(__m128i a, int imm8) -> __m128i
* [ ] _mm_srli_epi64(__m128i a, int imm8) -> __m128i
* [ ] _mm_srli_si128(__m128i a, int imm8) -> __m128i
* [ ] _mm_store_pd(double* mem_addr, __m128d a) -> void
* [ ] _mm_store_pd1(double* mem_addr, __m128d a) -> void
* [x] _mm_store_ps(float* mem_addr, __m128 a) -> void
* [ ] _mm_store_ps1(float* mem_addr, __m128 a) -> void
* [ ] _mm_store_sd(double* mem_addr, __m128d a) -> void
* [ ] _mm_store_si128(__m128i* mem_addr, __m128i a) -> void
* [ ] _mm_store_ss(float* mem_addr, __m128 a) -> void
* [ ] _mm_store1_pd(double* mem_addr, __m128d a) -> void
* [ ] _mm_store1_ps(float* mem_addr, __m128 a) -> void
* [ ] _mm_storeh_pd(double* mem_addr, __m128d a) -> void
* [ ] _mm_storeh_pi(__m64* mem_addr, __m128 a) -> void
* [ ] _mm_storel_epi64(__m128i* mem_addr, __m128i a) -> void
* [ ] _mm_storel_pd(double* mem_addr, __m128d a) -> void
* [ ] _mm_storel_pi(__m64* mem_addr, __m128 a) -> void
* [ ] _mm_storer_pd(double* mem_addr, __m128d a) -> void
* [ ] _mm_storer_ps(float* mem_addr, __m128 a) -> void
* [ ] _mm_storeu_pd(double* mem_addr, __m128d a) -> void
* [ ] _mm_storeu_ps(float* mem_addr, __m128 a) -> void
* [ ] _mm_storeu_si128(__m128i* mem_addr, __m128i a) -> void
* [ ] _mm_storeu_si16(void* mem_addr, __m128i a) -> void
* [ ] _mm_storeu_si32(void* mem_addr, __m128i a) -> void
* [ ] _mm_storeu_si64(void* mem_addr, __m128i a) -> void
* [ ] _mm_stream_pd(double* mem_addr, __m128d a) -> void
* [ ] _mm_stream_pi(__m64* mem_addr, __m64 a) -> void
* [ ] _mm_stream_ps(float* mem_addr, __m128 a) -> void
* [ ] _mm_stream_si128(__m128i* mem_addr, __m128i a) -> void
* [ ] _mm_stream_si32(int* mem_addr, int a) -> void
* [ ] _mm_stream_si64(__int64* mem_addr, __int64 a) -> void
* [ ] _mm_sub_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_sub_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_sub_epi64(__m128i a, __m128i b) -> __m128i
* [ ] _mm_sub_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_sub_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_sub_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_sub_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_sub_si64(__m64 a, __m64 b) -> __m64
* [ ] _mm_sub_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_subs_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_subs_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_subs_epu16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_subs_epu8(__m128i a, __m128i b) -> __m128i
* [x] _MM_TRANSPOSE4_PS(__m128 row0, __m128 row1, __m128 row2, __m128 row3)
* [ ] _mm_ucomieq_sd(__m128d a, __m128d b) -> int
* [ ] _mm_ucomieq_ss(__m128 a, __m128 b) -> int
* [ ] _mm_ucomige_sd(__m128d a, __m128d b) -> int
* [ ] _mm_ucomige_ss(__m128 a, __m128 b) -> int
* [ ] _mm_ucomigt_sd(__m128d a, __m128d b) -> int
* [ ] _mm_ucomigt_ss(__m128 a, __m128 b) -> int
* [ ] _mm_ucomile_sd(__m128d a, __m128d b) -> int
* [ ] _mm_ucomile_ss(__m128 a, __m128 b) -> int
* [ ] _mm_ucomilt_sd(__m128d a, __m128d b) -> int
* [ ] _mm_ucomilt_ss(__m128 a, __m128 b) -> int
* [ ] _mm_ucomineq_sd(__m128d a, __m128d b) -> int
* [ ] _mm_ucomineq_ss(__m128 a, __m128 b) -> int
* [ ] _mm_undefined_pd(void) -> __m128d
* [ ] _mm_undefined_ps(void) -> __m128
* [ ] _mm_undefined_si128(void) -> __m128i
* [ ] _mm_unpackhi_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpackhi_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpackhi_epi64(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpackhi_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpackhi_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_unpackhi_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_unpacklo_epi16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpacklo_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpacklo_epi64(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpacklo_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_unpacklo_pd(__m128d a, __m128d b) -> __m128d
* [x] _mm_unpacklo_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_xor_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_xor_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_xor_si128(__m128i a, __m128i b) -> __m128i
