### ISSUE TITLE
SSE3 Mega Checklist

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/hektor#6]
For entertainment purposes only, I'm checking off boxes if I use an intrinsic at least once within the lib.

Kept up to date as often as I remember to do it.

* [ ] _mm_addsub_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_addsub_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_hadd_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_hadd_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_hsub_pd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_hsub_ps(__m128 a, __m128 b) -> __m128
* [ ] _mm_lddqu_si128(__m128i const* mem_addr) -> __m128i
* [ ] _mm_loaddup_pd(double const* mem_addr) -> __m128d
* [ ] _mm_movedup_pd(__m128d a) -> __m128d
* [ ] _mm_movehdup_ps(__m128 a) -> __m128
* [ ] _mm_moveldup_ps(__m128 a) -> __m128
