### ISSUE TITLE
SSE4.1 Mega Checklist

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/hektor#8]
For entertainment purposes only, I'm checking off boxes if I use an intrinsic at least once within the lib.

Kept up to date as often as I remember to do it.

* [ ] _mm_blend_epi16(__m128i a, __m128i b, const int imm8) -> __m128i
* [ ] _mm_blend_pd(__m128d a, __m128d b, const int imm8) -> __m128d
* [ ] _mm_blend_ps(__m128 a, __m128 b, const int imm8) -> __m128
* [ ] _mm_blendv_epi8(__m128i a, __m128i b, __m128i mask) -> __m128i
* [ ] _mm_blendv_pd(__m128d a, __m128d b, __m128d mask) -> __m128d
* [ ] _mm_blendv_ps(__m128 a, __m128 b, __m128 mask) -> __m128
* [ ] _mm_ceil_pd(__m128d a) -> __m128d
* [ ] _mm_ceil_ps(__m128 a) -> __m128
* [ ] _mm_ceil_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_ceil_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_cmpeq_epi64(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cvtepi16_epi32(__m128i a) -> __m128i
* [ ] _mm_cvtepi16_epi64(__m128i a) -> __m128i
* [ ] _mm_cvtepi32_epi64(__m128i a) -> __m128i
* [ ] _mm_cvtepi8_epi16(__m128i a) -> __m128i
* [ ] _mm_cvtepi8_epi32(__m128i a) -> __m128i
* [ ] _mm_cvtepi8_epi64(__m128i a) -> __m128i
* [ ] _mm_cvtepu16_epi32(__m128i a) -> __m128i
* [ ] _mm_cvtepu16_epi64(__m128i a) -> __m128i
* [ ] _mm_cvtepu32_epi64(__m128i a) -> __m128i
* [ ] _mm_cvtepu8_epi16(__m128i a) -> __m128i
* [ ] _mm_cvtepu8_epi32(__m128i a) -> __m128i
* [ ] _mm_cvtepu8_epi64(__m128i a) -> __m128i
* [ ] _mm_dp_pd(__m128d a, __m128d b, const int imm8) -> __m128d
* [ ] _mm_dp_ps(__m128 a, __m128 b, const int imm8) -> __m128
* [ ] _mm_extract_epi32(__m128i a, const int imm8) -> int
* [ ] _mm_extract_epi64(__m128i a, const int imm8) -> __int64
* [ ] _mm_extract_epi8(__m128i a, const int imm8) -> int
* [ ] _mm_extract_ps(__m128 a, const int imm8) -> int
* [ ] _mm_floor_pd(__m128d a) -> __m128d
* [ ] _mm_floor_ps(__m128 a) -> __m128
* [ ] _mm_floor_sd(__m128d a, __m128d b) -> __m128d
* [ ] _mm_floor_ss(__m128 a, __m128 b) -> __m128
* [ ] _mm_insert_epi32(__m128i a, int i, const int imm8) -> __m128i
* [ ] _mm_insert_epi64(__m128i a, __int64 i, const int imm8) -> __m128i
* [ ] _mm_insert_epi8(__m128i a, int i, const int imm8) -> __m128i
* [ ] _mm_insert_ps(__m128 a, __m128 b, const int imm8) -> __m128
* [ ] _mm_max_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_max_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_max_epu16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_max_epu32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_min_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_min_epi8(__m128i a, __m128i b) -> __m128i
* [ ] _mm_min_epu16(__m128i a, __m128i b) -> __m128i
* [ ] _mm_min_epu32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_minpos_epu16(__m128i a) -> __m128i
* [ ] _mm_mpsadbw_epu8(__m128i a, __m128i b, const int imm8) -> __m128i
* [ ] _mm_mul_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_mullo_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_packus_epi32(__m128i a, __m128i b) -> __m128i
* [ ] _mm_round_pd(__m128d a, int rounding) -> __m128d
* [ ] _mm_round_ps(__m128 a, int rounding) -> __m128
* [ ] _mm_round_sd(__m128d a, __m128d b, int rounding) -> __m128d
* [ ] _mm_round_ss(__m128 a, __m128 b, int rounding) -> __m128
* [ ] _mm_stream_load_si128(__m128i * mem_addr) -> __m128i
* [ ] _mm_test_all_ones(__m128i a) -> int
* [ ] _mm_test_all_zeros(__m128i a, __m128i mask) -> int
* [ ] _mm_test_mix_ones_zeros(__m128i a, __m128i mask) -> int
* [ ] _mm_testc_si128(__m128i a, __m128i b) -> int
* [ ] _mm_testnzc_si128(__m128i a, __m128i b) -> int
* [ ] _mm_testz_si128(__m128i a, __m128i b) -> int
