### ISSUE TITLE
SSE4.2 Mega Checklist

### ISSUE THREAD

**Issue by Lokathor** [Lokathor/hektor#9]
For entertainment purposes only, I'm checking off boxes if I use an intrinsic at least once within the lib.

Kept up to date as often as I remember to do it.

* [ ] _mm_cmpestra(__m128i a, int la, __m128i b, int lb, const int imm8) -> int
* [ ] _mm_cmpestrc(__m128i a, int la, __m128i b, int lb, const int imm8) -> int
* [ ] _mm_cmpestri(__m128i a, int la, __m128i b, int lb, const int imm8) -> int
* [ ] _mm_cmpestrm(__m128i a, int la, __m128i b, int lb, const int imm8) -> __m128i
* [ ] _mm_cmpestro(__m128i a, int la, __m128i b, int lb, const int imm8) -> int
* [ ] _mm_cmpestrs(__m128i a, int la, __m128i b, int lb, const int imm8) -> int
* [ ] _mm_cmpestrz(__m128i a, int la, __m128i b, int lb, const int imm8) -> int
* [ ] _mm_cmpgt_epi64(__m128i a, __m128i b) -> __m128i
* [ ] _mm_cmpistra(__m128i a, __m128i b, const int imm8) -> int
* [ ] _mm_cmpistrc(__m128i a, __m128i b, const int imm8) -> int
* [ ] _mm_cmpistri(__m128i a, __m128i b, const int imm8) -> int
* [ ] _mm_cmpistrm(__m128i a, __m128i b, const int imm8) -> __m128i
* [ ] _mm_cmpistro(__m128i a, __m128i b, const int imm8) -> int
* [ ] _mm_cmpistrs(__m128i a, __m128i b, const int imm8) -> int
* [ ] _mm_cmpistrz(__m128i a, __m128i b, const int imm8) -> int
* [ ] _mm_crc32_u16(unsigned int crc, unsigned short v) -> unsigned int
* [ ] _mm_crc32_u32(unsigned int crc, unsigned int v) -> unsigned int
* [ ] _mm_crc32_u64(unsigned __int64 crc, unsigned __int64 v) -> unsigned __int64
* [ ] _mm_crc32_u8(unsigned int crc, unsigned char v) -> unsigned int
